resources:
    App\GeneratedEntity\NSFields:
        shortName: Fields
        types:
            - Fields
        operations:
            fields_get_collection:
                method: GET
                class: ApiPlatform\Metadata\GetCollection
                shortName: Fields
                normalizationContext:
                    enable_max_depth: true
                    groups:
                        - nodes_sources_base
                        - nodes_sources_default
                        - urls
                        - tag_base
                        - translation_base
                        - document_display
                        - document_thumbnails
                        - document_display_sources
                        - nodes_sources_boolean
                        - nodes_sources_geo
            fields_get:
                method: GET
                class: ApiPlatform\Metadata\Get
                shortName: Fields
                normalizationContext:
                    groups:
                        - nodes_sources
                        - node_listing
                        - urls
                        - tag_base
                        - translation_base
                        - document_display
                        - document_thumbnails
                        - document_display_sources
                        - nodes_sources_boolean
                        - nodes_sources_geo
